# Initialization

In [50]:
from HITS import run_hits_algorithm
from sim_rank import sim_rank
from page_rank import page_rank
from utility.utils import initialize_graph_from_file
import numpy as np
import time

# Parameter

In [21]:
iteration = 30
damping_factor = 0.1
decay_factor = 0.7

# Graph_1

In [55]:
graph_file = '../inputs/graph_1.txt'
graph = initialize_graph_from_file(graph_file)

## HITS Algorithm 

In [85]:
start_time = time.time()
run_hits_algorithm(graph, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

auth_list, hub_list = graph.get_authority_hub_lists()

# Convert to NumPy arrays
auth_array = np.array(auth_list)
hub_array = np.array(hub_list)

# Print to STDOUT
print("Authority:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in auth_array), end="]\n")
print("Hub:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in hub_array), end="]\n")

Execution time: 0.01807 seconds
Authority:
[0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.005 0.000 0.000 0.000 0.000 0.000 0.000 0.003 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.002 0.003 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.003 0.001 0.005 0.001 0.000 0.000 0.001 0.009 0.002 0.000 0.003 0.000 0.000 0.096 0.000 0.000 0.000 0.000 0.000 0.000 0.002 0.000 0.000 0.000 0.000 0.000 0.000 0.003 0.000 0.000 0.003 0.002 0.000 0.009 0.000 0.000 0.000 0.004 0.000 0.000 0.006 0.000 0.000 0.000 0.000 0.000 0.000 0.003 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.002 0.056 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.003 0.000 0.000 0.003 0.000 0.000 0.003 0.000 0.000 0.000 0.094 0.001 0.000 0.003 0.000 0.000 0.001 0.000 0.004 0.000 0.000 0.007 0.028 0.001 0.000 0.000 0.000 0.000 0.000 0.010 0.002 0.000 0.000 0.002 0.000 0.001 0.038 0.000 0.001 0.001 0.000 0.000 0.015 0.003 0.002 0.000 0.000 0.002 0.

## PageRank Algorithm

In [64]:
start_time = time.time()
page_rank(graph, damping_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")
pagerank_result = graph.get_pagerank()

# Print to STDOUT
print("PageRank:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in pagerank_result), end="]\n")

Execution time: 0.00184 seconds
PageRank:
[0.200 0.200 0.200 0.200 0.200]


## SimRank Algorithm

In [66]:
# Run the SimRank algorithm
start_time = time.time()
simrank_result = sim_rank(graph, decay_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

# Print to STDOUT
print("Decay Factor:")
print(decay_factor)
print("SimRank:")
print(simrank_result)

Execution time: 0.00367 seconds
Decay Factor:
0.7
SimRank:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Graph_2

In [67]:
graph_file = '../inputs/graph_2.txt'
graph = initialize_graph_from_file(graph_file)

## HITS Algorithm 

In [69]:
start_time = time.time()
run_hits_algorithm(graph, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
auth_list, hub_list = graph.get_authority_hub_lists()
print(f"Execution time: {elapsed_time_rounded} seconds")

# Convert to NumPy arrays
auth_array = np.array(auth_list)
hub_array = np.array(hub_list)

# Print to STDOUT
print("Authority:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in auth_array), end="]\n")
print("Hub:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in hub_array), end="]\n")

Execution time: 0.00027 seconds
Authority:
[0.200 0.200 0.200 0.200 0.200]
Hub:
[0.200 0.200 0.200 0.200 0.200]


## PageRank Algorithm

In [71]:
start_time = time.time()
page_rank(graph, damping_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")
pagerank_result = graph.get_pagerank()

# Print to STDOUT
print("PageRank:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in pagerank_result), end="]\n")

Execution time: 0.0025 seconds
PageRank:
[0.193 0.193 0.193 0.193 0.193]


## SimRank Algorithm

In [72]:
# Run the SimRank algorithm
start_time = time.time()
simrank_result = sim_rank(graph, decay_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

# Print to STDOUT
print("Decay Factor:")
print(decay_factor)
print("SimRank:")
print(simrank_result)

Execution time: 0.00362 seconds
Decay Factor:
0.7
SimRank:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Graph_3

In [73]:
graph_file = '../inputs/graph_3.txt'
graph = initialize_graph_from_file(graph_file)

## HITS Algorithm 

In [74]:
start_time = time.time()
run_hits_algorithm(graph, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

auth_list, hub_list = graph.get_authority_hub_lists()

# Convert to NumPy arrays
auth_array = np.array(auth_list)
hub_array = np.array(hub_list)

# Print to STDOUT
print("Authority:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in auth_array), end="]\n")
print("Hub:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in hub_array), end="]\n")

Execution time: 0.00019 seconds
Authority:
[0.191 0.309 0.309 0.191]
Hub:
[0.191 0.309 0.309 0.191]


## PageRank Algorithm

In [75]:
start_time = time.time()
page_rank(graph, damping_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")
pagerank_result = graph.get_pagerank()

# Print to STDOUT
print("PageRank:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in pagerank_result), end="]\n")

Execution time: 0.00224 seconds
PageRank:
[0.172 0.328 0.328 0.172]


## SimRank Algorithm

In [76]:
# Run the SimRank algorithm
start_time = time.time()
simrank_result = sim_rank(graph, decay_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

# Print to STDOUT
print("Decay Factor:")
print(decay_factor)
print("SimRank:")
print(simrank_result)

Execution time: 0.00185 seconds
Decay Factor:
0.7
SimRank:
[[1.    0.    0.538 0.   ]
 [0.    1.    0.    0.538]
 [0.538 0.    1.    0.   ]
 [0.    0.538 0.    1.   ]]


# Graph_4

In [77]:
graph_file = '../inputs/graph_4.txt'
graph = initialize_graph_from_file(graph_file)

## HITS Algorithm 

In [78]:
start_time = time.time()
run_hits_algorithm(graph, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

auth_list, hub_list = graph.get_authority_hub_lists()

# Convert to NumPy arrays
auth_array = np.array(auth_list)
hub_array = np.array(hub_list)

# Print to STDOUT
print("Authority:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in auth_array), end="]\n")
print("Hub:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in hub_array), end="]\n")

Execution time: 0.00039 seconds
Authority:
[0.139 0.178 0.201 0.140 0.201 0.056 0.084]
Hub:
[0.275 0.048 0.109 0.199 0.184 0.117 0.069]


## PageRank Algorithm

In [79]:
start_time = time.time()
page_rank(graph, damping_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")
pagerank_result = graph.get_pagerank()

# Print to STDOUT
print("PageRank:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in pagerank_result), end="]\n")

Execution time: 0.00285 seconds
PageRank:
[0.288 0.161 0.139 0.107 0.183 0.055 0.066]


## SimRank Algorithm

In [80]:
# Run the SimRank algorithm
start_time = time.time()
simrank_result = sim_rank(graph, decay_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

# Print to STDOUT
print("Decay Factor:")
print(decay_factor)
print("SimRank:")
print(simrank_result)

Execution time: 0.00949 seconds
Decay Factor:
0.7
SimRank:
[[1.    0.243 0.232 0.239 0.221 0.303 0.175]
 [0.243 1.    0.294 0.256 0.295 0.169 0.343]
 [0.232 0.294 1.    0.34  0.275 0.339 0.341]
 [0.239 0.256 0.34  1.    0.23  0.427 0.427]
 [0.221 0.295 0.275 0.23  1.    0.159 0.3  ]
 [0.303 0.169 0.339 0.427 0.159 1.    0.155]
 [0.175 0.343 0.341 0.427 0.3   0.155 1.   ]]


# Graph_5

In [81]:
graph_file = '../inputs/graph_5.txt'
graph = initialize_graph_from_file(graph_file)

## HITS Algorithm 

In [82]:
start_time = time.time()
run_hits_algorithm(graph, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

auth_list, hub_list = graph.get_authority_hub_lists()

# Convert to NumPy arrays
auth_array = np.array(auth_list)
hub_array = np.array(hub_list)

# Print to STDOUT
print("Authority:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in auth_array), end="]\n")
print("Hub:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in hub_array), end="]\n")

Execution time: 0.01898 seconds
Authority:
[0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.005 0.000 0.000 0.000 0.000 0.000 0.000 0.003 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.002 0.003 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.003 0.001 0.005 0.001 0.000 0.000 0.001 0.009 0.002 0.000 0.003 0.000 0.000 0.096 0.000 0.000 0.000 0.000 0.000 0.000 0.002 0.000 0.000 0.000 0.000 0.000 0.000 0.003 0.000 0.000 0.003 0.002 0.000 0.009 0.000 0.000 0.000 0.004 0.000 0.000 0.006 0.000 0.000 0.000 0.000 0.000 0.000 0.003 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.002 0.056 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.003 0.000 0.000 0.003 0.000 0.000 0.003 0.000 0.000 0.000 0.094 0.001 0.000 0.003 0.000 0.000 0.001 0.000 0.004 0.000 0.000 0.007 0.028 0.001 0.000 0.000 0.000 0.000 0.000 0.010 0.002 0.000 0.000 0.002 0.000 0.001 0.038 0.000 0.001 0.001 0.000 0.000 0.015 0.003 0.002 0.000 0.000 0.002 0.

## PageRank Algorithm

In [83]:
start_time = time.time()
page_rank(graph, damping_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")
pagerank_result = graph.get_pagerank()

# Print to STDOUT
print("PageRank:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in pagerank_result), end="]\n")

Execution time: 0.1289 seconds
PageRank:
[0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.004 0.004 0.002 0.005 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.003 0.002 0.002 0.002 0.002 0.004 0.002 0.002 0.004 0.005 0.002 0.003 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.015 0.002 0.003 0.002 0.002 0.002 0.002 0.002 0.002 0.003 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.003 0.002 0.005 0.002 0.006 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.011 0.003 0.002 0.002 0.002 0.003 0.002 0.002 0.002 0.002 0.003 0.002 0.003 0.002 0.002 0.002 0.002 0.002 0.015 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.003 0.002 0.002 0.002 0.005 0.002 0.002 0.002 0.002 0.002 0.002 0.003 0.002 0.002 0.002 0.002 0.002 0.002 0.006 0.002 0.002 0.002 0.004 0.002 0.003 0.002 0.002 0.002 0.002 0.002 0.00

## SimRank Algorithm

In [84]:
# Run the SimRank algorithm
start_time = time.time()
simrank_result = sim_rank(graph, decay_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

# Print to STDOUT
print("Decay Factor:")
print(decay_factor)
print("SimRank:")
print(simrank_result)

Execution time: 35.78503 seconds
Decay Factor:
0.7
SimRank:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


# Graph_6

In [86]:
graph_file = '../inputs/graph_6.txt'
graph = initialize_graph_from_file(graph_file)

## HITS Algorithm

In [87]:
start_time = time.time()
run_hits_algorithm(graph, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

auth_list, hub_list = graph.get_authority_hub_lists()

# Convert to NumPy arrays
auth_array = np.array(auth_list)
hub_array = np.array(hub_list)

# Print to STDOUT
print("Authority:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in auth_array), end="]\n")
print("Hub:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in hub_array), end="]\n")

Execution time: 0.05168 seconds
Authority:
[0.000 0.001 0.000 0.000 0.000 0.001 0.000 0.001 0.002 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.002 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.002 0.000 0.005 0.000 0.000 0.000 0.001 0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.001 0.000 0.000 0.028 0.001 0.000 0.000 0.000 0.000 0.003 0.002 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.000 0.028 0.002 0.001 0.002 0.000 0.000 0.000 0.001 0.001 0.000 0.001 0.000 0.000 0.001 0.000 0.000 0.000 0.004 0.000 0.000 0.000 0.001 0.000 0.001 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.013 0.001 0.000 0.002 0.000 0.004 0.001 0.000 0.004 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.001 0.000 0.001 0.000 0.000 0.000 0.

## PageRank Algorithm

In [88]:
start_time = time.time()
page_rank(graph, damping_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")
pagerank_result = graph.get_pagerank()

# Print to STDOUT
print("PageRank:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in pagerank_result), end="]\n")

Execution time: 0.4601 seconds
PageRank:
[0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.002 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.003 0.001 0.001 0.001 0.001 0.001 0.002 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.003 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.002 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.002 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.002 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.00

## SimRank Algorithm

In [89]:
pass

# ibm-5000

In [90]:
graph_file = '../inputs/ibm-5000.txt'
graph = initialize_graph_from_file(graph_file)

## HITS Algorithm 

In [91]:
start_time = time.time()
run_hits_algorithm(graph, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")

auth_list, hub_list = graph.get_authority_hub_lists()

# Convert to NumPy arrays
auth_array = np.array(auth_list)
hub_array = np.array(hub_list)

# Print to STDOUT
print("Authority:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in auth_array), end="]\n")
print("Hub:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in hub_array), end="]\n")

Execution time: 0.037 seconds
Authority:
[0.000 0.000 0.130 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.009 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.128 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.00

## PageRank Algorithm

In [92]:
start_time = time.time()
page_rank(graph, damping_factor, iteration)
end_time = time.time()
elapsed_time = end_time - start_time
elapsed_time_rounded = round(elapsed_time, 5)
print(f"Execution time: {elapsed_time_rounded} seconds")
pagerank_result = graph.get_pagerank()

# Print to STDOUT
print("PageRank:")
print("[", end="")
print(" ".join(f"{value:.3f}" for value in pagerank_result), end="]\n")

Execution time: 0.35935 seconds
PageRank:
[0.000 0.000 0.038 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.009 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.011 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.037 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.004 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.0

## SimRank Algorithm

In [93]:
pass